# Generated by Django 5.1.5 on 2025-02-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_acls', '0004_netbox_acls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclextendedrule',
            name='logging',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
