# Generated by Django 5.1.5 on 2025-02-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_acls', '0005_aclextendedrule_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclextendedrule',
            name='counter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
